// <auto-generated />
namespace ImageBoard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class wdwdwa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wdwdwa));
        
        string IMigrationMetadata.Id
        {
            get { return "201705280607039_wdwdwa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
