// <auto-generated />
namespace ImageBoard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FillDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FillDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091923101_FillDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
